users = [
  {first_name: "Test", 
   last_name: "User 2", 
   email: 'test@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: open('http://www.mileanhour.com/files/2010/2/redneck-prom.jpg'),  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
  {first_name: "Test", 
   last_name: "User 3", 
   email: 'test3@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
  {first_name: "Wolfgang Amadeus", 
   last_name: "Truckstop III", 
   email: 'truckstop@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://i2.kym-cdn.com/entries/icons/original/000/005/530/redneck-randall.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 4", 
   email: 'test4@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 5", 
   email: 'test5@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 6", 
   email: 'test6@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 7", 
   email: 'test7@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 8", 
   email: 'test8@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 9", 
   email: 'test9@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 10", 
   email: 'test10@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 11", 
   email: 'test11@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 12", 
   email: 'test12@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 13", 
   email: 'test13@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 14", 
   email: 'test14@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 15", 
   email: 'test15@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 16", 
   email: 'test16@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 17", 
   email: 'test17@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 18", 
   email: 'test18@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 19", 
   email: 'test19@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 20", 
   email: 'test20@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
     {first_name: "Test", 
   last_name: "User 21", 
   email: 'test21@test.com', 
   password: 'testtest',
   password_confirmation: 'testtest',
   user_image: 'http://www.mileanhour.com/files/2010/2/redneck-prom.jpg',  
   about: 'Hodor, hodor. Hodor. Hodor, hodor, hodor. Hodor hodor, hodor. Hodor hodor, hodor, hodor hodor. Hodor, hodor hodor...',
   start_weight: '300',
   goal_weight: '200'},
]

users.each do |user|
  User.create(
    first_name: user[:first_name],
    last_name: user[:last_name],
    email: user[:email],
    password: user[:password],
    password_confirmation: user[:password_confirmation],
    user_image: user[:user_image],
    about: user[:about],
    start_weight: user[:start_weight],
    goal_weight: user[:goal_weight]
  )
end